# TensorFlow란?

구글에서 만든 딥러닝 플랫폼으로 가장 많이 사용되는 딥러닝 라이브러리이다. 

1. 프레임워크   
    문제해결을 위한 기본 개념 구조. 개발할 수 있도록 필요한 기능들을 제공한다. 
    
2. 라이브러리  
    기능 구현에 있어서 필요한 비휘발성 자원의 모임.
    
    
- 우리의 학습은 2.0을 기준으로 진행한다.
- 러닝커브가 가파르다. 아래의 특징들이 텐서플로우를 어렵게 만든다.
    1. *'tensor'*의 개념
    2. 내부 실행 구조가 '*graph*'를 사용한  *'lazy evaluation'* 방식이다.
    

https://www.tensorflow.org/api_docs/python/tf


##  Ctrl + Enter를 누르면 실행이다.
## Alt + Enter를 누르면 실행 + 새로운 코드 입력할 수 있는 셀 생성이다.
## ESC -> M을 누르면 설명을 추가할 수 있는 란이 생긴다.
## ESC -> X를 누르면 해당 셀을 삭제할 수 있다.
## Enter를 누르면 셀에 입력 가능하다.
## ESC를 누르면 셀을 선택 가능하다.

In [4]:
import tensorflow as tf

# 1. Tensor(텐서)의 개념

> 텐서플로우에서 사용되는 `데이터를 담는 그릇`으로,  모든 원소가 동일한 type을 가지는 다차원 배열이다.

- numpy를 알고 있다면 numpy의 array와 동일하다. 
→ 실제로 numpy의 데이터 타입을 기본적으로 사용한다.


- tensorflow의 모든 데이터는 tensor를 통해 정의된다.


- 텐서가 선언되었다면 내부 데이터를 업데이트 할 수 없으며, 값이 갱신되는 대신, 갱신된 값으로 새로운 tensor가 생성되는 방식이다. 하지만 특정 텐서는 method를 사용하면 내부의 값을 갱신할 수 있다. (*tf.Variable*)


두 가지 중요한 속성 타입, 차원은 반드시 텐서에 정의되어야만 한다.

** 텐서를 선언할때 변수명을 구분되도록 선언하자.

# 1-1. 차원

텐서는 `다차원`배열이라고 정의하였다.   
차원의 갯수 즉, 데이터가 표현되는 축의 갯수를 rank라고 하는데, 모든 텐서는 rank값을 가진다.  
이 rank 값으로 데이터의 종류가 구별되는데, `.ndim` method를 통해서 rank를 알 수 있다.

## 1. scalar

rank = 0,  0차원의 데이터이다. 하나의 값을 가진다.

#### constant(상수)

텐서의 자료형으로, 프로그램 종료시까지 데이터가 변하지 않는 특성을 가지는 텐서이다.  

`tf.constant` 클래스를 통해 생성하며, 반드시 초기값이 존재해야한다.

In [8]:
# 정수

# 0차원 즉, 단 하나의 값을 가지는 텐서를 정의하였다.
scalar_1 = tf.constant(3)

print(scalar_1.ndim)
print(scalar_1)

# 실수
scalar_2 = tf.constant(3.14)
print(scalar_2.ndim)
print(scalar_2)

0
tf.Tensor(3, shape=(), dtype=int32)
0
tf.Tensor(3.14, shape=(), dtype=float32)


In [10]:
# 문자열
scalar_3 = tf.constant('안녕')

print(scalar_3)

# 단 한가지 값을 가지는 값은 모두 이렇게 표현된다.

scalar_4 = tf.constant(4.66)
print(scalar_4)

tf.Tensor(b'\xec\x95\x88\xeb\x85\x95', shape=(), dtype=string)
tf.Tensor(4.66, shape=(), dtype=float32)


## 2. vector

rank = 1, 1차원의 데이터로 하나의 축을 가지는 배열으로 생각하면 된다.

In [24]:
# 축이 하나라는 의미 X축 

vector_1 = tf.constant([3, 4])

print(vector_1)
print(vector_1.ndim)


# 내부 원소가 여러개를 가질 수 있지만 동일한 타입을 가져야만 합니다.
vector_2 = tf.constant([4, 4.44])

# type casting -> 정수, 실수 
print(vector_2)

# 동일한 내부 원소 타입을 가져야 한다.
# vector_3 = tf.constant(['안녕', 3])


vector_4 = tf.constant([1, 3, 5, 7])
print(vector_4)

tf.Tensor([3 4], shape=(2,), dtype=int32)
1
tf.Tensor([4.   4.44], shape=(2,), dtype=float32)
tf.Tensor([1 3 5 7], shape=(4,), dtype=int32)


## 3. matrix

rank = 2, 2차원의 데이터로  두개의 축을 가진 행렬의 형태를 가진다.

In [18]:
matrix_1 = tf.constant(
[
    [1, 2],
    [3, 4],
    [5, 6]
]
)

print(matrix_1)
print(matrix_1.ndim)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
2


## 이외의 다차원 텐서도 가능

In [26]:
multi_tensor = tf.constant([
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]],
])

print(multi_tensor)

print('-------------------')
print(multi_tensor.numpy())

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
-------------------
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]


In [20]:
multi_tensor.ndim

3

각 텐서들의 출력을 살펴보면 모두 내부 값 뿐 아니라, shape 도 함께 출력된다.   
shape는 텐서의 각 차원의 길이를 말한다.   
예로 다차원의 텐서의 첫 번째 차원의 길이는 3, 두 번째 차원의 길이는 2, 세 번째 차원의 길이는 5이기 때문에 해당 텐서의 shape는 (3, 2, 5)가 된다. 



모든 텐서는 차원의 갯수, 각 차원의 길이인 shape가 반드시 정의되어야한다.   
shape를 명시하여 정의하거나 초기값을 통해 자동으로 shape를 정의하는 과정이 명시되어야한다. 
이외에 shape와 같은 텐서에 대한 여러가지 개념을 아래에서 소개한다.  
  

- numpy를 알고 있다면 numpy의 array와 동일하다.   
→ 실제로 numpy의 데이터 타입을 기본적으로 사용한다.  


- tensorflow의 모든 데이터는 tensor를 통해 정의된다.


- 텐서가 선언되었다면 내부 데이터를 업데이트 할 수 없으며, 값이 갱신되는 대신, 갱신된 값으로 새로운 tensor가 생성되는 방식이다. 하지만 특정 텐서는 method를 사용하면 내부의 값을 갱신할 수 있다. (*tf.Variable*)
  

# 1-2. 텐서에 대한 여러가지 개념


1. rank
2. shape
3. axis, dim
4. size

### rank

텐서의 차원의 갯수

In [27]:
print(scalar_1.ndim)

0


In [29]:
print(vector_1.ndim)
print(matrix_1.ndim)
print(multi_tensor.ndim)

1
2
3


## shape

텐서의 각 차원의 길이 (element의 수)

#### shape를 계산하는 방법

1. []를 하나씩 제거하여 내부의 원소 갯수를 계수한다.
2. 내부 원소 중 하나를 선택하여 1의 순서를 반복한다.



```
# shape 계산 예제


   0, 1, 2, 3, 4


# 1번 수행 -> 가장 바깥의 []을 제거하여 원소의 갯수를 센다 -> 3
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]],
  [[10, 11, 12, 13, 14],
   [15, 16, 17, 18, 19]],
  [[20, 21, 22, 23, 24],
   [25, 26, 27, 28, 29]]

# 2번 수행 -> 배열의 하나의 원소를 택하여 1번을 수행한다.
  [[0, 1, 2, 3, 4],
   [5, 6, 7, 8, 9]]

# 다시 1번 수행 -> 가장 바깥의 []을 제거하여 원소의 갯수를 센다 -> 2
 [0, 1, 2, 3, 4],
 [5, 6, 7, 8, 9]

# 다시 2번 수행 -> 배열의 하나의 원소를 택하여 1번을 수행한다.
 [0, 1, 2, 3, 4]

# 다시 1번 수행 -> 가장 바깥의 []을 제거하여 원소의 갯수를 센다 -> 5
	0, 1, 2, 3, 4

# 즉, shape는 (3, 2, 5)
```

In [30]:
tf.constant([3, 4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 4])>

## axis, dim

텐서의 특정 차원

In [32]:
print(scalar_1.shape)
print(vector_1.shape)
print(matrix_1.shape)
print(multi_tensor.shape)

()
(2,)
(3, 2)
(3, 2, 5)


In [34]:
# 3번째 차원의 길이 즉, axis = 3 
print(multi_tensor.shape[2])

5


## size

텐서의 총 원소 갯수

모든 차원의 길이의 곱

`tf.size()`를 통해 데이터 size를 알 수 있다.

In [37]:
print(tf.size(scalar_1))
print(vector_1)

print(tf.size(vector_1))
print(tf.size(matrix_1))

print(multi_tensor.shape)
print(tf.size(multi_tensor))


tf.Tensor(1, shape=(), dtype=int32)
tf.Tensor([3 4], shape=(2,), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)
tf.Tensor(6, shape=(), dtype=int32)
(3, 2, 5)
tf.Tensor(30, shape=(), dtype=int32)


# 1-3. 원소의 타입

텐서는 기본적으로 numpy.array을 사용한다.  
텐서는 모든 원소가 동일한 타입을 가진다.(numpy.array와 동일한 개념이다.) 주요 특징은 아래와 같다.

- 주로 숫자 데이터를 사용하기 때문에 float, int를 사용하는데 이 때 값의 표현범위를 정의하기 위해 사용되는 bit 수를 뒤에 추가한다.   
    예로 float32, float64, int32, int64 가 사용된다.   
    

- 문자열 등 수가 아닌 다른 타입도 사용할 수 있지만 하나의 텐서에는 하나의 타입만 사용할 수 있다. (모든 원소 가 동일한 타입이어야 하므로)


- 텐서의 데이터는 직사각형의 구조이어야 한다.   
    > 텐서를 구성하는 축(axis, dim)마다 모든 요소의 크기가 같다는 것을 의미
    > 모든 요소의 크기가 동일하지 않다면 shape를 정의할 수 없다.
    > 희소행렬을 처리하는 SparseTensor처럼 직사각형이 아닌 것도 있지만 학습 범위 밖이다.
    ```
    # ex.1 (3, ?)
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8]
    ]

    # ex.2 
    [ [[0, 1, 3, 4],
       [5, 6, 7, 8, 9]],
      [[10, 11, 12, 13, 14],
       [15, 19]],
      [[20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31]],])
    ```

__모든 텐서는 원소의 타입인 dtype이 반드시 정의되어야한다. dtype을 명시하거나 초기값을 통해 자동으로 dtype를 정의한다.__

요약 

## 텐서

1. 텐서플로우에서 사용하는 데이터를 담는 그릇이다.
2. 텐서는 반드시 '차원'과 '원소의 타입'을 가진다. 

차원 -> shape,   

원소의 타입 -> dtype 

차원이 여러 개일 수 있는데,   
- 0차원의 텐서는 스칼라, tf.constant(3) 
- 1차원의 텐서는 벡터, tf.constant([3, 4])
- 2차원의 텐서는 매트릭스, tf.constant([[3, 4], [1, 2]]) 
- 3차원이상부터는 다차원 텐서라고 부른다. ...


#### 텐서가 가지는 값은  .numpy() 통해 알 수 있다.

#### 각 차원의 길이는 .shape를 통해 알 수 있다.

#### 텐서가 가지는 모든 원소의 타입은 동일해야한다. 

- 타입이 동일하지 않으면 에러가 난다. 

# 1-4. 텐서의 자료형

텐서를 `데이터를 담는 그릇`으로 정의하였다.   
텐서의 자료형은 여러가지이지만 그 중에 두 개만 설명하고자 한다.   
이 그릇들은 앞에서 설명했던 데이터의 차원과 원소의 타입이 명시되어야한다는 특성은 그대로 가진다.  

## constant(상수)

프로그램 종료시까지 데이터가 변하지 않는 특성을 가지는 텐서이다. 

- tf.constant 클래스를 통해 생성하며, 반드시 초기값이 존재해야한다.  
    → shape, dtype을 명시하지 않아도 가능하지만 명시하는 것이 좋다.
     
     
- 상수와 동일하게 값이 변하지 않는다.

In [40]:
#1. 초기값을 선언하지 않는 constant

# [1, 3] -> dtype int, shape (2,)
print(tf.constant([1,3]))

tf.constant([1, 3], dtype=tf.float32)


tf.constant(shape=(1, 3), dtype = tf.float32)

tf.Tensor([1 3], shape=(2,), dtype=int32)


TypeError: constant() missing 1 required positional argument: 'value'

In [45]:
#2. constant선언 

vector_2 = tf.constant([1, 3], dtype=tf.float32)


# python 
x = 3
y = 3

print(id(x))
print(id(y))


# constant
scalar_1 = tf.constant(3)

print(id(scalar_1))

scalar_2 = tf.constant(3)

print(id(scalar_2))

140711240279904
140711240279904
1953818096560
1953818096384


## Variable (변수)

변수는 프로그램, 모델 내에서 값을 공유하는 영구적인 `상태`를 저장하는 텐서이다.  
tensorflow, keras는 모든 가중치를 Variable으로 저장한다. 이 Variable의 특성은 아래와 같다.

- tf.Variable 클래스를 통해 생성하며, 반드시 초기값이 존재해야한다.  
    -> shape, dtype을 명시하지않아도 가능하지만 명시하는 것이 좋다.

In [51]:
# constant 텐서
vector_1 = tf.constant([1, 2])
print(vector_1)

# variable 텐서
var_1 = tf.Variable([1, 2])

print(var_1)

# 텐서의 모든 데이터는 numpy()
var_1.numpy()

tf.Tensor([1 2], shape=(2,), dtype=int32)
<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([1, 2])>


array([1, 2])

- 값이 변하지 않는다. 하지만 `assign()` method를 통해서 갱신이 가능하다.  
    > 값이 변한 것처럼 보이지만 변경된 값으로 새로운 텐서가 만들어진 것이다. (텐서의 연산에서 설명)  
    
    > assign() 사용시에는 동일한 shape, dtype의 데이터로만 갱신이 가능하다.  
    ( 새로운 텐서가 생성되는 방식이 아닌 값만 갱신되는 방식이므로 선언된 메모리의 재사용을 위해서)
    

- 프로그램 종료시점에 garbage collect(할당된 메모리를 회수하는 것)가 진행된다.   
    > 즉, 프로그램 종료시점까지 내부의 데이터는 보존된다.
    
    
    
- name 속성값을 선언하여 해당 변수의 이름을 지정하는 것이 좋다.   
    > 지정하지 않으면 default의 값으로 생성된다.  
    
    > 이 후, 디버깅이나 모델저장시 유용하다.

In [53]:
# 재할당을 진행하는 함수
var_1 = tf.Variable([1, 2])
print('재할당 전의 주소 : ', id(var_1))


var_1.assign([3,4])
print('재할당 후의 주소 : ', id(var_1))


재할당 전의 주소 :  1953974047792
재할당 후의 주소 :  1953974047792


TypeError: Cannot convert [1.44, 2.12] to EagerTensor of dtype int32

In [57]:
# Cannot convert [1.0, 2.0] to EagerTensor of dtype int32 (type casting)
# 반드시 재할당하는 값의 dtype이  이전의 dtype동일해야함
#var_1.assign([1.44, 2.12])


# dtype 뿐 만 아니라 shape도 동일해야하는가?
# [3 4]
print(var_1.shape)

var_1.assign([3, 4, 5])

# assign의 경우에는 재할당하는 값이 동일한 shape, 동일한 dtype을 가져야한다.

(2,)


ValueError: Shapes (2,) and (3,) are incompatible

In [59]:
# 덧셈을 진행하는 함수
print(var_1.numpy())

# 반드시 shape 동일해야한다.
var_1.assign_add([3, 4])

# assign의 경우에는 재할당하는 값이 동일한 shape, 동일한 dtype을 가져야한다.
# 동일하지 않은 shape
#var_1.assign_add([3, 4, 5])

# 동일하지 않은 dtype
var_1.assign_add([3.44, 4.14])

print(var_1.numpy())

[ 9 12]


TypeError: Cannot convert [3.44, 4.14] to EagerTensor of dtype int32

## assign 함수

- 주소값이 동일한 텐서에 값이 변경된다. -> 텐서는 값이 변경되지 않는다.  
- 텐서를 하나 만들어서 동일한 주소값에 넣기 때문이다.  


그러면, 실제로 텐서에 값을 변경하게 되면 새로운 텐서가 생성되는가?

In [60]:
# 재할당 전의 주소
print(id(var_1))

# 값을 더하여 재할당
var_1.assign_add([3, 4])

# 재할당 후의 주소
print(id(var_1))

1953974047792
1953974047792


In [64]:
# 그러면, 실제로 텐서에 값을 변경하게 되면 새로운 텐서가 생성되는가?
print(var_1)

#var_1.assign_add([3, 4])
# numpy 연산을 통해 텐서의 값이 변경되었다.

print(id(var_1))

var_1 + [3, 4]

print(id(var_1))

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15, 20])>
1953974047792
1953974047792


#### numpy 연산, tensorflow가 제공하는 연산으로 텐서의 값을 변경하더라도 동일한 주소값을 가지도록 새로운 텐서를 만들어서 사용한다.

# 1-5. 텐서의 연산

텐서는 기본적으로 값이 변하지 않기 때문에 연산의 결과가 텐서에 반영되는 것이 아닌 새로운 텐서로 반환된다.   
또한 `다차원`배열인 텐서는 기본적인 자료구조를 numpy의 구조로 사용하기 때문에 numpy의 연산과 동일하다.   
여러가지 기본적인 연산의 예제를 통해 알아보자.  

## 1. element-wise calculation

numpy의 연산은 기본적으로 원소별 계산이 수행된다.  
- numpy는  broadcasting을 지원하기 때문에 피연산자 간의 shape가 다를지라도 연산에 적합하도록 변환하여 수행한다.  

In [68]:
# 현재 변수 텐서의 shape (2, )
print(var_1)

print(var_1 + 1)


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([15, 20])>
tf.Tensor([16 21], shape=(2,), dtype=int32)


In [70]:
print(multi_tensor)


print(multi_tensor + 1)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
tf.Tensor(
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]

 [[11 12 13 14 15]
  [16 17 18 19 20]]

 [[21 22 23 24 25]
  [26 27 28 29 30]]], shape=(3, 2, 5), dtype=int32)


In [72]:
print(multi_tensor * 3)ㅔ

print(multi_tensor - 6)

tf.Tensor(
[[[ 0  3  6  9 12]
  [15 18 21 24 27]]

 [[30 33 36 39 42]
  [45 48 51 54 57]]

 [[60 63 66 69 72]
  [75 78 81 84 87]]], shape=(3, 2, 5), dtype=int32)
tf.Tensor(
[[[-6 -5 -4 -3 -2]
  [-1  0  1  2  3]]

 [[ 4  5  6  7  8]
  [ 9 10 11 12 13]]

 [[14 15 16 17 18]
  [19 20 21 22 23]]], shape=(3, 2, 5), dtype=int32)


In [73]:
# 텐서의 원소의 타입이 다른 numpy연산 

# numpy연산을 수행할 때는 shape가 달라도 가능하지만 dtype이 달라서는 안된다.
print(multi_tensor + 1.7)

InvalidArgumentError: cannot compute AddV2 as input #1(zero-based) was expected to be a int32 tensor but is a float tensor [Op:AddV2]

In [79]:
# 단일값 덧셈이 아닌 다차원 값 덧셈
print(multi_tensor)

# 다차원 값이더라도 numpy연산이 가능하다.
print(multi_tensor.shape)
print(multi_tensor + [1, 2, 3, 4, 5])

# numpy연산을 수행하는 텐서의 마지막 차원의 크기가 동일하지 않으면 수행하지 못한다.
print(multi_tensor + [1, 2, 3, 4])


tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)
(3, 2, 5)
tf.Tensor(
[[[ 1  3  5  7  9]
  [ 6  8 10 12 14]]

 [[11 13 15 17 19]
  [16 18 20 22 24]]

 [[21 23 25 27 29]
  [26 28 30 32 34]]], shape=(3, 2, 5), dtype=int32)


InvalidArgumentError: Incompatible shapes: [3,2,5] vs. [4] [Op:AddV2]

In [82]:
# tensorflow에서 제공하는 연산 함수를 사용하게 됩니다.

matrix_1 = tf.constant([
    [1, 1],
    [1, 1]
])

# 단순 텐서 연산을 tf.add()함수로 제공합니다.
print(tf.add(matrix_1, 1))

# numpy 연산인 단순 사칙 연산
print(matrix_1 + 1)

# numpy연산을 하느냐, 텐서플로우에서 제공하는 함수를 사용하느냐 
# 텐서플로우에서 제공하는 함수를 사용하면 추후 연산을 수행하는 과정에서 최적화 발생합니다. 

tf.Tensor(
[[2 2]
 [2 2]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[2 2]
 [2 2]], shape=(2, 2), dtype=int32)


- tensorflow에서도 사칙연산을 method로 제공한다. 하지만 numpy의 연산과 다르게 broadcasting이  지원되지 않으므로 피연산자간 동일한 shape가 필요하다.

## 2. matrix calculation

원소별 계산이 아닌 행렬연산의 경우, tensorflow의 내장된 method를 사용한다.

행렬연산이기 때문에 shape를 맞춰야 진행이 가능하다.

In [ ]:
# numpy 연산의 경우에는 원소별 연산, matrix연산의 경우에는 내장함수를 사용해야한다.

## 3. reducer function

텐서의 shape에 무관하게 데이터들을 통해 단일 값의 결과로 나오는 연산을 reducer function 이라고 한다. 

In [85]:
print(matrix_1)

# reduce_sum() 
# 해당 텐서의 모든 원소를 더한 값을 반환하는 함수 -> 1개의 단일값이 나옴

print(tf.reduce_sum(matrix_1))

# 평균을 구하는 reduce_mean
print(tf.reduce_mean(matrix_1))

tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(1, shape=(), dtype=int32)


## 4. gradient of Variable

tensorflow, keras에서는 모든 가중치의 값을 Variable에 저장한다고 하였다.   
학습 과정에서 가중치에 대한 미분 값을 기준으로 값이 갱신되기 때문에 텐서에 대한 미분값을 계산하는 것은 매우 중요하다.   
텐서의 미분 연산에 대한 클래스 `tf.GradientTape`를 이용하여 자동으로 미분값을 계산하고 추적하는 방법을 알아보자.  



### `tf.GradientTape`

생성된 객체는 `watch()` 를 통해 기록되는 텐서의 연산의 과정(연산식)을 기억해두고 `gradient()` 선언 시점에  미분값을 계산한다.
> gradient() 를 통해 미분 연산값을 계산하고 나면 메모리에 저장되어있던 연산의 과정을 지운다. 



- Variable은 기본적으로 미분의 대상이기 때문에 watch() 로 선언하지 않아도 된다.


- 미분 연산을 위해서는 반드시 dtype이 float으로 가져야한다.

In [ ]:
# reducer -> 

In [90]:
# 변수를 정의합니다.

x = tf.Variable([1, 2, 3, 4], dtype = tf.float32)

# with문 내에서 구하고자 하는 미분 값의 연산과정을 정의합니다.
with tf.GradientTape() as t:
    # y = (1 + 2 + 3 + 4)
    y = tf.reduce_sum(x)
    print(y.numpy())
    
    # y을 제곱한다.
    # z = y**2
    z = tf.multiply(y, y)
    print(z.numpy())
    # z = tf.pow(y, 2)

# 미분값을 구하자.
dz_dy = t.gradient(z, y)
print(dz_dy.numpy())    

# dz_dx ? 
# t라는 미분값을 추적하는 GradientTape 클래스의 인스턴스는 반드시 한번의 미분만 계산이 가능합니다.
# t라는 인스턴스가 미분 연산 후에 연산과정을 모두 지워버리기 때문입니다.
dz_dx = t.gradient(z, x)
print(dz_dx)

10.0
100.0
20.0


RuntimeError: GradientTape.gradient can only be called once on non-persistent tapes.

<img src="./education_images/1-1_formula.png" alt="Drawing" style="width: 400px;"/>



- 기준 변수에 대해서 파생되는 변수들에 대한 미분 값을 구하고 싶을 때 persistent=True 옵션을 사용한다.    
    이 때는 반드시 사용된 메모리에 대한 반환을 직접 해줘야한다.

In [97]:
# 미분을 수행할 텐서를 정의
# constant를 float를 정의하지 않았기 때문에 에러가 발생하였다.
x = tf.constant(3, dtype = tf.float32)

# 미분을 계산할 연산과정을 with문 내에서 정의
# 여러 번의 미분 연산을 수행할 수 있도록 연산과정을 계속 기억하라!
with tf.GradientTape(persistent = True) as t:
    # 미분을 계산하는 객체 t에게 x라는 텐서를 미분할 것이니까 연산과정을 기억하세요.
    t.watch(x)
    
    # y = x**2
    y = tf.pow(x, 2)
    
    # z = y**2
    z = tf.pow(y, 2)
    

# 미분값을 계산합니다
dz_dy = t.gradient(z, y)

# 여러번의 미분 값을 계산할 수 있습니다.
dz_dx = t.gradient(z, x)
print(dz_dx.numpy())
    

108.0


<img src="./education_images/1-2_formula.png" alt="Drawing" style="width: 400px;"/>

<img src="./education_images/1-3_quiz.png" alt="Drawing" style="width: 400px;"/>

1. 텐서의 제곱은 `tf.math.pow()`를 사용한다.
2. 텐서의 루트는 `tf.math.sqrt()`를 사용한다.

In [ ]:
a = tf.constant(3, dtype = tf.float32)
b = tf.constant(4, dtype =tf.float32)


#### 식으로 간단하게 미분값을 계산할 수 있는 일반 선형연산 뿐 아니라 식으로 표현이 어려운 if, for문에 대한 추적도 가능하다.



In [ ]:
# 
def f(x,y):
    output = 1.0
    for i in range(y):
        if i > 1 and i < 5:
            output = tf.multiply(output, x)
    return output

# 1일차 정리

## 텐서의 기초

텐서 - 텐서플로우에서 사용하는 값들을 담는 그릇. 

텐서는 shape, dtype을 가져야한다.

1. shape

shape 텐서가 가지는 차원의 크기 입니다.

shape = (3, 2) 을 가지는 텐서는 차원의 갯수는 2입니다. 각 차원의 크기는 3, 2입니다.

텐서는 대괄호([])의 갯수에 따라 차원의 갯수가 결정됩니다.



2. dtype

텐서가 가지는 값들의 타입을 dtype이라고 한다.

int32, float32, string 여러가지 타입을 정의할 수 있습니다.

반드시 하나의 텐서는 하나의 타입만을 가질 수 있습니다.


## tensor의 자료형


1. constant 

프로그램 내에서 변하지 않는 값을 가지는 텐서

2. Variable

프로그램이 자동으로 변경하려고 하는 텐서

둘 모두 텐서가 가져야하는 shape, dtype이 반드시 정의되어야 한다.  
이전의 여러 예제들을 통해서 텐서의 값들을 확인할 때, 초기값을 사용하여 선언하였습니다. 

### 즉, 두 텐서 모두 초기값이 선언되어야 합니다.  

In [1]:
import tensorflow as tf

In [4]:
# 텐서의 shape가 (3, 2)인경우
test_tensor = tf.constant([
    [1, 2], [3, 4], [5, 6]
])

print(test_tensor)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)
tf.Tensor(3, shape=(), dtype=int32)


In [6]:
# 텐서의 차원이 존재하지 않음
print(tf.constant(3))

# 텐서의 차원이 1개임.
print(tf.constant([1, 2]))

tf.Tensor(3, shape=(), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


In [7]:
# 텐서의 dtype이 일정하지 않은 경우
tf.constant([1, '안녕'])

ValueError: Can't convert Python sequence with mixed types to Tensor.

In [8]:
# 텐서의 초기값이 선언되지 않은 경우 초기값을 제외하고 shape, dtype을 모두 정의하였다.
tf.constant( shape= (3, 3), dtype = tf.int32)

TypeError: constant() missing 1 required positional argument: 'value'

In [9]:
tf.Variable( shape= (3, 3), dtype = tf.int32)

ValueError: initial_value must be specified.

# Graph

지금까지 배운 것을 잠깐 정리해보면,

1. 텐서는 값의 변경이 불가능하기 때문에 새로운 텐서가 생성됩니다.

2. 1번의 특성으로 인해 모든 텐서 간의 연산은 값의 변경이 아닌 연산 결과값을 가진 텐서가 새롭게 생성되는 방식이다.

이러한 특성으로 우리는 (피연산자 - 연산자 - 연산의 결과값)에 해당하는 모든 연산의 과정을 텐서로 표현할 수 있는데 연산의 과정을 텐서로 표현한 것이 바로 `Graph`이다. 아래의 간단한 예제들을 보고 그래프의 개념을 이해해보자.

<img src="./education_images/1-4_formula.png" alt="Drawing" style="width: 300px;"/>

<img src="./education_images/1-5_graph.png" alt="Drawing" style="width: 100px;"/>

## 그래프 모드로 연산하기

우리가 graph를 이해하기 어려운 이유는 연산을 수행하는 과정이 코드를 작성할때 마다 수행되는 방식이기 때문입니다.

### 그래프 모드로 연산하는 방법

1. 함수를 선언하여 연산과정을 서술한다.

2. @tf.function 데코레이터를 사용하여 해당 함수를 그래프 모드로 연산한다는 것을 명시합니다.


In [10]:
# 2 * 2 * 3 * 4 * 5 의 작업을 수행하는 함수

def calculation():
    x = tf.constant(2)
    
    # 2 * 2
    y = x * 2
    print(y)
    
    # 2 * 2 * 3
    z = y * 3
    print(z)
    
    # 2 * 2 * 3 * 4
    a = z * 4
    print(a)
    
    # 2 * 2 * 3 * 4 * 5
    b = a * 5
    print(b)
    
    return b

In [11]:
calculation()

tf.Tensor(4, shape=(), dtype=int32)
tf.Tensor(12, shape=(), dtype=int32)
tf.Tensor(48, shape=(), dtype=int32)
tf.Tensor(240, shape=(), dtype=int32)


<tf.Tensor: shape=(), dtype=int32, numpy=240>

In [12]:
@tf.function
def calculation_graph():
    x = tf.constant(2)
    
    # 2 * 2
    # 2 * 2 가 수행되는 것이 아니라, 2 * 2 의 연산의 결과를 넣을 '자리'만 표현하는 것.
    y = x * 2
    print(y)
    
    # 2 * 2 * 3
    z = y * 3
    print(z)
    
    # 2 * 2 * 3 * 4
    a = z * 4
    print(a)
    
    # 2 * 2 * 3 * 4 * 5
    b = a * 5
    print(b)
    
    return b

In [14]:
# 그래프 모드로 함수를 수행하게 되면 해당 함수 값을 사용할 때까지 연산작업을 실시하지 않습니다.
result = calculation_graph()

print(result.numpy())

240


## 그래프 정리


그래프 모드는 연산 과정을 코드 선언시 수행하는 것이 아니라, 최종 연산 과정의 결과값이 필요할 때, 연산을 수행하는 것을 의미합니다.

텐서플로우 내에서는 그래프 모드를 내부적으로 수행하는 방식으로 여러 모델이나 기능들을 실행합니다.

## 그래프 연산

2.0 이전의 버전의 tensorflow는 내부적으로 모든 연산에 대해서 그래프를 구현한 뒤,  `Lazy evaluation`으로 연산을 수행한다. 

> `Lazy evaluation`이란, 연산의 결과값이 필요할 때까지 연산을 실시하지 않고 미뤄두었다가 연산값이 호출되는 시점에 연산을 실시하는 기법이다.


  즉, 텐서로 연산을 수행하는 코드를 작성하고 실행한다고 해서 연산이 수행되는 것이 아니라 단순히 연산의 그래프를 그리는 행위일 뿐, 실제 연산의 수행은 연산값을 호출할 때 이루어진다. 

### 1. 프로그램이 실행되면 연산의 과정에 따라 텐서들을 연결하여 그래프로 만든다.  

- 이시점에서 연산의 최적화가 발생한다. 연산이 복잡하고 많을수록 더 많은 개선이 일어난다.
- 내부 연산을 분할하여 병렬처리가 가능하도록 구현
- 연산을 단순화하도록 구현

### 2. 하나의 그래프가 수행되는 절차 단위인 session은 그래프를 device 상에서 수행될 수 있도록 C코드로 변환한다.

- CPU, GPU에서 수행될 수 있도록 device에 대해 최적화를 진행한다.
- C 코드로 수행하기 때문에 python의 속도의 한계를 극복할 수 있게 된다.
- python 인터프리터에 대한 환경의 제약조건이 사라지게 되면서 배포환경에 대해 자유롭다.


### 3. `run()` 코드를 통해 연산값을 호출하면 연산을 수행하고 결과값을 반환한다.

연산을 즉시 수행하는 것이 아닌 최대한 늦추는 기법을 사용하게 되면서, 내부 연산에 대한 최적화, device에 대한 최적화, 속도 개선등의 이점을 얻을 수 있었다. 하지만 연산에 대한 결과값을 즉시 볼 수 없기 때문에 디버깅하기 어렵고, 연산이 즉시 수행되는 `Eager evaluation`에 익숙해져있는 개발자들의 생산성이 떨어질 수 밖에 없었다. 때문에 Tensorflow 2.0에서는 그래프를 사용하지 않고 연산의 결과값을 코드 실행시점에 즉시 볼 수 있도록  `Eager evaluation`을 채택하였다. 그럼에도 불구하고 연산 및 학습의 속도를 위해 데코레이터를 통해 연산의 과정을 그래프로 만들어 수행하는 기능도 제공하고 있다. 데코레이터를 활용한 간단한 예제를 살펴보자.


- 데코레이팅 된 함수 내에서 호출된 함수 또한 그래프의 대상이 된다.


-  우리가 사용하는 함수를 단순히 데코레이터로 래핑하는 것만으로도 속도를 높일 수 있다. 하지만 복잡하지 않은 계산에 대해서는 오히려 그래프 및 그래프 조각호출에 사용하는 시간이 더 많을 수 있다.

In [ ]:
def inner_function(x, y, b):
    x = tf.matmul(x,y)
    x = x + b
    return x

@tf.function
def outer_function(x):
    y = tf.constant([[2.0], [3.0]])
    b = tf.constant(4.0)
    
    return inner_function(x, y, b)

outer_function(tf.constant([[1.0, 2.0]])).numpy()